### ISSUE TITLE
Duplicate GpsPositions added

### ISSUE THREAD

**Issue by legonigel** [auvsi-suas/interop#13]
After running the test server for some time it was severely slowed down. I believe this is related to the rediculous number of GpsPosition items. Currently my copy of the server has 201064 gpsposition items. More than 10% of these items are duplicate of a gps position already in the database.  I stopped checking for duplicates at 10% because I confirmed my suspicion of a large number of duplicate gps positions. 

I have not looked at the code enough to verify this, but I believe most of these GpsPosition elements come from the posted telemetry items.

**Comment by pmtischler** [comment]
I'm happy to help debug the issue with you, but let's not jump to conclusions just yet :)

To my knowledge, we only save a `GpsPosition` in:
* [UAS telemetry upload](https://github.com/auvsi-suas/interop/blob/9b98df13502caa746e7ba7f6ce84d3c8afd5f400/server/auvsi_suas/views/telemetry.py#L75)
* [Target submission](https://github.com/auvsi-suas/interop/blob/9b98df13502caa746e7ba7f6ce84d3c8afd5f400/server/auvsi_suas/views/targets.py#L151)

Neither code paths contain a loop or multiple save calls. Our code does not dedupe `GpsPositions` on write, it dedupes the positions on read (e.g. as part of post-mission evaluation), so it is entirely possible you are uploading duplicate data.

201064 positions is not a lot. At 10Hz that is ~5.6 hours of uploads, we sustained longer at competition without any issue. The `GpsPosition` model has 3 fields which are at most 8 bytes each (id, latitude, longitude), so that is only ~4.6MB, a very small size. The Postgres database can handle much larger. We [set our database-side caching to 1GB](https://github.com/auvsi-suas/interop/blob/9b98df13502caa746e7ba7f6ce84d3c8afd5f400/setup/puppet_files/auvsi_suas/manifests/postgresql_setup.pp#L28), so serving should be cached in memory completely. With database journaling, our [disabling of synchronous commits via fsync](https://github.com/auvsi-suas/interop/blob/9b98df13502caa746e7ba7f6ce84d3c8afd5f400/setup/puppet_files/auvsi_suas/manifests/postgresql_setup.pp#L50), and [512MB window for checkpointing](https://github.com/auvsi-suas/interop/blob/9b98df13502caa746e7ba7f6ce84d3c8afd5f400/setup/puppet_files/auvsi_suas/manifests/postgresql_setup.pp#L38), we shouldn't have any issues dealing with 4.6MB of writes.

* What does "slow" mean?
 + Are interoperability requests having high latency?
 + Is interoperability throughput limited? 
 + Is this not related to interoperability requests, but rather one of the admin interfaces (Django or the SUAS one)?
 + How are you measuring this?
* Have you checked that you aren't sending duplicate data?
 + How did you check 10% of duplicates? You said you stopped because you confirmed your suspicion- did you do this by eye? Did you execute a SQL query (and if so, what was it)?
 + Can you set your system up so it starts clean, only sends UAS Telemetry via upload, and then compare the number of logged POST requests (the debug log) to the number of telemetry positions? Please let me know the sizes of each.
* What is you complete deployment scenario? Vagrant? Dedicated machine? Virtual machine? Specs on these?

**Comment by prattmic** [comment]
To add to this, we don't dedup GpsPosition objects for a reason. These
objects represent a position in space with floating point numbers. In a
real world scenario (i.e., competition), the aircraft is moving around and
it would be *extremely* unlikely for the aircraft to report exactly the
same location twice. Thus, performing deduplication buys us little. The
probability of duplicates goes up if the aircraft is sitting still on the
ground, but it is still not worth the effort (or thw extra SQL query) to do
deduplication.

In testing, I can imagine replaying a previous flight in a loop, which
would create duplicates if the data is sampled at the same points.

**Comment by legonigel** [comment]
> What does "slow" mean?
> Is this not related to interoperability requests, but rather one of the admin interfaces (Django or the SUAS one)?

I suppose I should explain where I discovered this being a problem. Visiting `/admin/auvsi_suas/missionconfig/add/` is nearly impossible. The Django admin interface for creating a new mission config. It tries to load a list of all gps positions into some of the fields. On my computer connecting to the webserver over the network using chromium the tab loading the admin interface takes more than 30 minutes to load and uses most of my processor while loading. Right now this tab is using about 1.9gb.

> Have you checked that you aren't sending duplicate data?

I have not checked exactly. Because we are running Ardupilot SILT simulation in a loop it is possible that the plane simply passed over the exact same location again.

> How did you check 10% of duplicates? You said you stopped because you confirmed your suspicion- did you do this by eye? Did you execute a SQL query (and if so, what was it)?

I wrote a quick python script to look at the exported data, because I don't have enough experience with SQL to write the correct query. I ran `./manage.py dumpdata auvsi_suas.GpsPosition --indent 2 > gps_positions.json` to get the data into a json file. Then I ran [this script](https://gist.github.com/legonigel/08a0ca050d94e7cce644) in the python cobut stopped it early and checked the length of the `dup_fields` list. 

> Can you set your system up so it starts clean, only sends UAS Telemetry via upload, and then compare the number of logged POST requests (the debug log) to the number of telemetry positions? Please let me know the sizes of each.

If you still think this is necessary, then let me know I will work on this next week.

> What is you complete deployment scenario? Vagrant? Dedicated machine? Virtual machine? Specs on these

We are using a dedicated machine. It is running Ubuntu 14.04.3 LTS (GNU/Linux 3.19.0-30-generic x86_64). The machine is running a Core2 Duo E8400 @ 3.00GHz with 4gb of ram.

**Comment by prattmic** [comment]
Ah, loading 200k entries for every GpsPosition dropdown in the admin interface would indeed be quite slow. :)

It is simple to disable those dropdowns. I will put up a pull request to do so soon.

**Comment by pmtischler** [comment]
Ah yes, the Django admin interface does get slow in default configuration even in a small size. We haven't spent a huge time optimizing it, and that workflow is likely something we haven't tried ourselves. We don't edit the `MissionConfig` post start of missions so we likely never visited that page after receiving data. For multi-missions, we have in past dumped the data, flushed (cleared) the database, and started fresh. If we needed it we would just load it back in.

After a quick search, it seems we just need to specify the [raw_id_fields](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields) `ModelAdmin` property in our [admin interface configuration](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/admin.py#L20). This will replace the list with multi-select with an input field that accepts comma separated IDs. It won't be as usable, but it'll scale at least.

In the long-term, we should just have our own admin interface. After the existing required feature requests, we can tackle such an interface.

---

Yea the `O(N^2)` will make it slow quickly :) Maybe try something like:
```
gps_pos = eval(open('gps_positions.json', 'r'))
deduped_fields = set([item['fields'] for item in gps_pos])
print 'Original Size: %d, Deduped Size: %d' % (len(gps_pos), len(deduped_fields))
```

There were two symptoms that we were trying to address: slowness and duplicate data. We've tracked the slowness to a known issue with the Django admin interface, but we haven't identified the cause of the duplicate data yet. Based on the code, I'd bet the server isn't the source of duplicates. So yes, please perform the log analysis so we can determine whether it's on your side or ours.

**Comment by pmtischler** [comment]
For reference, we saw some teams at competition have bugs in their interoperability implementations that led to duplicate data (e.g. one team sent the same position over and over despite the UAS moving).

**Comment by legonigel** [comment]
@prattmic Thanks for fixing the admin interface issue! 

@pmtischler I will look at the duplicate GPS positions, but you are probably correct that the issue is on our side. If I do find otherwise, I will reopen the issue. 

On a side note the code to find the `deduped_fields` doesn't work because the `item['fields']` is a dictionary which is not a hashable type. I think there is probably a way to make it so, but I just wanted to check if there was duplicate data.

**Comment by pmtischler** [comment]
Ah good catch. You just need to convert to the frozen equivalent, E.g.

frozenset(items[...

And sounds good.
