### ISSUE TITLE
Add GPS time to the telemetry interface

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#151]
For more accurate scoring not dependent on ordering or latency. Should be added with latency bound, which can be removed if we ever remove real-time requirement.

**Comment by prattmic** [comment]
Hm, I'm not sure about this one. GPS receivers often report time at 1Hz and may or may not correct for leap seconds (GPS is currently 17s ahead of UTC. GPS does broadcast the correction factor to receivers, but I do not know if all use it.)

Telemetry should not be received out of order. Jitter between packets could be problematic, but I'm not sure it is a big issue. We could request an arbitrary timestamp (i.e. some system clock like time since boot), but I'm not sure all autopilots have that readily available either (and they may reboot).

**Comment by pmtischler** [comment]
I wasn't aware of that and it seems out of scope for us to fix or mitigate. Closing this issue.
