### ISSUE TITLE
test.sh

### ISSUE THREAD

**Issue by patiladitya1011** [auvsi-suas/interop#185]
while running the script it shows me up this error.
django.db.utils.OperationalError: FATAL:  the database system is starting up
FATAL:  the database system is starting up

**Comment by pmtischler** [comment]
The repo is now deployed with Docker- you shouldn't have to run this
script.

On Oct 7, 2016 2:11 PM, "patiladitya1011" <notifications@github.com> wrote:

while running the script it shows me up this error.
django.db.utils.OperationalError: FATAL: the database system is starting up
FATAL: the database system is starting up

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/auvsi-suas/interop/issues/185>, or mute the thread

**Comment by patiladitya1011** [comment]
Thank you very much for the help.

On 07-Oct-2016 11:45 pm, "Phillip Tischler" <notifications@github.com>
wrote:
>
> The repo is now deployed with Docker- you shouldn't have to run this
> script.
>
> On Oct 7, 2016 2:11 PM, "patiladitya1011" <notifications@github.com>
wrote:
>
> while running the script it shows me up this error.
> django.db.utils.OperationalError: FATAL: the database system is starting
up
