### ISSUE TITLE
Waypoint Navigation Evaluation Bug

### ISSUE THREAD

**Issue by ethmur** [auvsi-suas/interop#250]
On a fresh install. I created a Mission Config object with 3 waypoints. I simulated a waypoint navigation by creating 3 UAS Telemetry objects using the Django Admin interface. The 3 UAS telemetry objects had the exact same latitude, longitude, and altitude as the mission waypoints. Then I evaluated. As shown in the screenshot below, full points were given for all 3 waypoints. This is the expected behavior.

![waypoint_navigation_evaluation_hit_waypoints_123](https://cloud.githubusercontent.com/assets/12011400/25457869/c0d60d52-2aa5-11e7-9a85-95c31859b309.jpg)

However, I then deleted the 1st UAS Telemetry object and re-evaluated. As shown in the screenshot below, zero points were given for all 3 waypoints. This is not the expected behavior, because only the 1st waypoint was missed. The 2nd and 3rd waypoints were hit perfectly. Full points should have been given for the 2nd and 3rd waypoints.

![waypoint_navigation_evaluation_hit_waypoints_23](https://cloud.githubusercontent.com/assets/12011400/25458070/6ef58a7a-2aa6-11e7-9eb4-20f632743b3e.jpg)

At least I believe that is not the expected behavior, based on the rulebook. In the Mission Demonstration, Autonomous Flight, Waypoint Accuracy section, it says "Each waypoint will be weighted equally, and the ratio of points received per waypoint will be max(0, (100ft − distance) / 100ft)".

Thanks.

**Comment by pmtischler** [comment]
This looks like the server still implements the requirement from last year
where you can't get points for a waypoint unless you hit all the ones
preceding it. I think the rules could be interpreted as such, but it was my
intention to change it this year to what you're expecting.

Thank you for discovering this, I'll look into it shortly.

On Apr 26, 2017 5:41 PM, "ethmur" <notifications@github.com> wrote:

On a fresh install. I created a Mission Config object with 3 waypoints. I
simulated a waypoint navigation by creating 3 UAS Telemetry objects using
the Django Admin interface. The 3 UAS telemetry objects had the exact same
latitude, longitude, and altitude as the mission waypoints. Then I
evaluated. As shown in the screenshot below, full points were given for all
3 waypoints. This is the expected behavior.

[image: waypoint_navigation_evaluation_hit_waypoints_123]
<https://cloud.githubusercontent.com/assets/12011400/25457869/c0d60d52-2aa5-11e7-9a85-95c31859b309.jpg>

However, I then deleted the 1st UAS Telemetry object and re-evaluated. As
shown in the screenshot below, zero points were given for all 3 waypoints.
This is not the expected behavior, because only the 1st waypoint was
missed. The 2nd and 3rd waypoints were hit perfectly. Full points should
have been given for the 2nd and 3rd waypoints.

[image: waypoint_navigation_evaluation_hit_waypoints_23]
<https://cloud.githubusercontent.com/assets/12011400/25458070/6ef58a7a-2aa6-11e7-9eb4-20f632743b3e.jpg>

At least I believe that is not the expected behavior, based on the
rulebook. In the Mission Demonstration, Autonomous Flight, Waypoint
Accuracy section, it says "Each waypoint will be weighted equally, and the
ratio of points received per waypoint will be max(0, (100ft − distance) /
100ft)".

Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/auvsi-suas/interop/issues/250>, or mute the thread
