### ISSUE TITLE
Issue with updating the server

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#252]
Hi,

We tried to update the server using the provided documentation, however it appears that the user interface does not change. Specifically, we do not see any section in the "Edit Data" interface that allows us to score the mission. Is this a simple error to fix? Am I just missing something with the installation that is preventing the system from upgrading? The server successfully installs but it always contains the same outdated interface.

**Comment by pmtischler** [comment]
Please reread the docs, you're using the wrong interface.

On May 4, 2017 1:24 PM, "Vale" <notifications@github.com> wrote:

Hi,

We tried to update the server using the provided documentation, however it
appears that the user interface does not change. Specifically, we do not
see any section in the "Edit Data" interface that allows us to score the
mission. Is this a simple error to fix? Am I just missing something with
the installation that is preventing the system from upgrading? The server
successfully installs but it always contains the same outdated interface.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/auvsi-suas/interop/issues/252>, or mute the thread

**Comment by DarkmatterVale** [comment]
I am using the correct interface. As specified in the documentation, when I attempt to do the following

```
Provide Human Judge Data. The first step is to provide the manual judge data. Go to System > Edit Data. Select Mission judge feedbacks >> add. Fill out the object with the mission, user, and details about the team’s performance, and then save.
```

I cannot see a "Mission judge feedbacks" section. Below is a screenshot of what I see when I proceed to System > Edit Data.

![auvsi_suas_screenshot](https://cloud.githubusercontent.com/assets/6094957/25722648/de1e1010-30e2-11e7-8979-1545fd7d4c31.png)

**Comment by pmtischler** [comment]
Ah that's a different question- why is the model edit not appearing rather
than running the scoring tool.

It's a docker thing. You have an active container. You need to destroy and
recreate it before you can get the new code. You'll need to take special
steps if you want to retain database state.

**Comment by DarkmatterVale** [comment]
I tried running the following commands (which all succeeded):

```
sudo docker stop interop-server
sudo docker rm interop-server
sudo ./interop/server/run.sh
```

The interface still looks that same, however. I have the most up to date version of the git repository as well, and I can see the commits for adding the scoring functionality in the git log.

**Comment by pmtischler** [comment]
Try running docker pull and let me know if that helps.

**Comment by pmtischler** [comment]
Added instructions for docker pull via https://github.com/auvsi-suas/interop/commit/80f013d59dac2bd5252304ef02d1de20ba6782ed

**Comment by DarkmatterVale** [comment]
Thank you! That fixed the problem.
