### ISSUE TITLE
Question Regarding Why Team Evaluation Failing

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#305]
We have set up the interoperability server to simulate mission demonstrations. However, when we attempt to use the team evaluation function, we get a ```Server Error (500)```. This error only appears when evaluating a specific user.

I know this isn't a lot of data, but is there any simple reason as to why attempting to evaluate the team function would cause this error? We made sure that during the simulation we started mission time, created takeoff and landing events, and finally stopped mission time. Additionally, we submitted a ```Mission Judge Feedback``` object post mission.

**Comment by pmtischler** [comment]
Please post the contents of the server log.

**Comment by DarkmatterVale** [comment]
We currently have the interoperability server running via docker, and are unable to SSH into the instance to retrieve the log. Is there any way that we can view the log externally?

**Comment by pmtischler** [comment]
Please read the documentation:
* [Getting a shell into container](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html#auvsisuas-interop-server)
* [Debugging the server](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/debugging.html)

**Comment by DarkmatterVale** [comment]
I apologize for not reading the documentation thoroughly. I have attached a picture of the error to this post. Unfortunately, we are having issues with the computer running the interoperability server which is why I had to take a picture of the error with an external device.

After looking at the log, I believe that the error could be an issue with our ODCL submissions. Perhaps we missed something that the automatic score evaluation requires to operate properly?

![img_20180510_143214759](https://user-images.githubusercontent.com/6094957/39888926-5a09840c-5464-11e8-9567-1021143e3cdf.jpg)

**Comment by pmtischler** [comment]
Looks like you didn't define odlcs for the mission, which the server assumes is part of any mission. [This fix](https://github.com/auvsi-suas/interop/pull/306) should make the server return no score for odlc instead, you can [pull the latest docker image](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html#auvsisuas-interop-server) once its pushed.

The part of the docs you missed was [here](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html#mission-configuration) where it says:
> To configure a mission, create or edit the MissionConfig object to specify the desired flight boundaries, waypoints, **true objects** (for grading base objects), etc

That is, you need to add odlcs that are the 'true' result, link them to the MissionConfig, so that when the server gets team odlcs it can score them by comparing against the 'true' odlcs.

The server should have a more specialized admin UI for defining missions which includes such validation so you don't have to debug it. Unfortunately we haven't gotten to that yet.

**Comment by DarkmatterVale** [comment]
Thank you for the help! Our team really appreciates the thorough responses. We will fix our missions and update to the newest version of the interop server docker image.
