### ISSUE TITLE
Issue using interop_cli.py to forward MAVLink packets

### ISSUE THREAD

**Issue by manavgandhi17** [auvsi-suas/interop#307]
Good Evening,

I am with the AUVSI SUAS team at Virginia Tech - "Avis Impar". We are having an issue with integrating the provided interop scripts with MAVLink.  

Before getting into the problem, here is a bit of info on our setup.

We go directly from our team computer, running windows 10 to the "interop router", with no router dedicated to the team. The interop router is then connected to a computer running to a computer running Ubuntu 16.04 LTS and hosting the server. The server was setup exactly how it is outlined to be setup in the documention.

For connection testing, as we are doing now, dronekit is used to setup a simulation (thus the master port is tcp:127.0.0.1:5760). We run MAVLink on our team computer and split the outputs via the following line:

```python mavproxy.py --master=tcp:127.0.0.1:5760 --out=tcpin:127.0.0.1:14550 --out=tcpin:127.0.0.1:14551```
Then we connect to 127.0.0.1:14551 via MissionPlanner 
(note: mission planner is able to connect to both ports)

After logging into the server successfully, we run:
```python interop_cli.py --url http://10.10.130.2:8000 --username testuser --password testpass mavlink --device 127.0.0.1:14550```

However, after running this we are hit with the following error message: 
```CRITICAL: Did not receive MAVLink packet for over 10 seconds.```

We have tested both ports with MissionPlanner, and have ensured that both are active and sending MAVLink packets.

Is this an issue on our end? If so, we would appreciate any help in fixing it.

**Comment by pmtischler** [comment]
Yes, this is very likely an issue on your end and thus your responsibility to debug. The competition provides a mavproxy demo as an example only- we don't support MissionPlanner or mavproxy. Our understanding of those tools and your setup is limited.

> After logging into the server successfully, we run:

I'm not sure which server you're referring to. The interop CLI must be run from a team computer, not the judge computer hosting the interop server. I'm guessing you're referring to exec-ing into a Docker container.

Note you've invoked the mavproxy in a different way than how our example does in the [docs](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html#mavlink-ardupilot-integration). Reading through some mavproxy code, the default for a device is UDP if protocol is not specified. So your different mavproxy invocation is outputting TCP rather than default, whereas your interop CL invocation is listening for default of UDP.

**Comment by manavgandhi17** [comment]
Thank you so much for the help, switching the devices from TCP to UDP fixed the issue for us - thus we were able to upload the data successfully.
