### ISSUE TITLE
Add all static mission parameters to interop

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#411]
* Air drop boundary.
* UGV drive position.
* Lost comms point.

**Comment by halloweentown** [comment]
As the rules do not include possible values, may I suggest adding an updated section for possible "target" characteristics like the old wiki had. 

I haven't updated the wiki myself as I only had time to review the Colors section so far.

Link to old wiki below.

- [Target Type](http://people.cs.ksu.edu/~chandanchowdhury/spykat/spec.html?-highlight=color#TargetTypes) 
- [Orientations](http://people.cs.ksu.edu/~chandanchowdhury/spykat/spec.html?highlight=color#Orientations)
- [Shapes](http://people.cs.ksu.edu/~chandanchowdhury/spykat/spec.html?highlight=color#Shapes)
- [Colors](http://people.cs.ksu.edu/~chandanchowdhury/spykat/spec.html?highlight=color#Colors)

**Comment by pmtischler** [comment]
@halloweentown it is linked off the API specification in the Wiki.

**Comment by pmtischler** [comment]
*Edit*: Just moved the documentation into the README so it's more discoverable and easier for me to maintain. There is a link in it to the full API specification which includes an enum with all the valid values for those fields.

**Comment by halloweentown** [comment]
@pmtischler Thanks for promptly addressing this, and for pointing out the [API Specification link](https://github.com/auvsi-suas/interop/blob/master/proto/interop_api.proto).

With your permission, i'd like to add the possible values to the read me.

Reason being, this issue was brought to my attention by mech eng students who couldn't find these easily (They were tasked with making new targets).

Also, in the spirit of reducing the barrier of entry for new students, I would also suggest leaving the wiki up _**with a disclaimer**_ that the updated version of the documentation is in the README.

**Comment by pmtischler** [comment]
@halloweentown Sorry, but we will not be adding it to the documentation. It was explicitly removed as part of switching to protos so that documentation is always accurate and up to date- the code is constrained by the proto API definition so it must be up to date. Unfortunately, as a volunteer organization, we don't have the human cycles to cater to everyone's preferred documentation and discovery strategy.

At this point I need to move on to other efforts.

**Comment by pmtischler** [comment]
Include the air drop and drive to location for SUAS 2020.
