### ISSUE TITLE
Scoring and Telemetry problem

### ISSUE THREAD

**Issue by enisteper1** [auvsi-suas/interop#465]
At first I installed last year's competition interop server and tested everything was cool.Then I removed all docker images and containers  installed latest interop. At the latest  interop I get  autonomous flight, obstacle avoidance, waypoint accuracy points as 0 and telemetryprequisite false .How can I fix this problem ?  
Also when I change an existing takeofforlandingevent and then evaluate I get "Infinite flight period, may be missing TakeoffOrLandingEvent." warning.When I add new events 1 for takeoff 1 for landing I get max and telemetry seconds as:
 "uasTelemetryTimeMaxSec": 314.0,
 "uasTelemetryTimeAvgSec": 314.0,

**Comment by pmtischler** [comment]
> How can I fix this problem ?

Sorry, but you haven't provided enough detail to debug your issue.

If you have false for telemetry prereq, then you can't get points for waypoint accuracy or obstacle avoidance as both are judged based on telemetry. Autonomous flight the section is scored entirely based on waypoint accuracy this year, so that's why the whole section is 0. You also need to submit a judge feedback and check the min flight time box, otherwise you get 0 no matter what (it's a mission prereq).

> when I change an existing takeofforlandingevent and then evaluate I get "Infinite flight period, may be missing TakeoffOrLandingEvent." warning.

When scoring a mission, the code looks for all `TakeoffOrLandingEvent` objects for the user and mission. First, check the user and mission are set correctly on your event objects. The code then checks for sequences of takeoffs followed by a landing. A takeoff is marked by true for "uas in air", and a landing by false for "uas in air". Second, check your two events have the right check box settings. If any of these are wrong, you'll get a takeoff or landing, but not both, and hence an "infinite" flight duration which indicates an interop admin operator error.

> When I add new events 1 for takeoff 1 for landing I get max and telemetry seconds as 314.0

If the max and average are equal to the time between takeoff and landing, that means it registered no telemetry between takeoff and landing. Check that your telemetry was sent in between the time range, and that the both the events and the telemetry are for the correct user.

**Comment by manavgandhi17** [comment]
Good Evening,

I am receiving a similar error with the same max and avg telemetry time which results in no scoring due to a lack of perceived telemetry. However, I have gone through and verified that the telemetry is present and the takeoff/landing events are situated correctly. Any assistance would be greatly appreciated...

Takeoff/Landing Events
![image](https://user-images.githubusercontent.com/24982420/147721133-254a35dc-1266-4ba7-9c29-18f037c1729d.png)

Small Portion of Submitted Telemetry:
![image](https://user-images.githubusercontent.com/24982420/147721154-50f3d1db-973f-4d47-a740-a018422381f1.png)

Scoring Report:
![image](https://user-images.githubusercontent.com/24982420/147721176-58dd32d1-2cd6-4f09-b6dd-48d700bc2fb0.png)

**Comment by pmtischler** [comment]
I've been able to reproduce this. I believe a bug may have been introduced in #439 (post 2019 competition, before any others). There is a double use of a generator in the `mission_evaluation` code which leaves one list empty.
