### ISSUE TITLE
Image thumbnail

### ISSUE THREAD

**Issue by cheikhKebeDia** [auvsi-suas/interop#471]
Hi Phil,
I have a problem when I try to send the thumbnail of an ODLC.
Basically I have my crop in the form of a base64 (which I transform into binary as stipulated in the readme of the interop). However I have a type 400 error.
I have attached pictures of my requests as well as the error I get through postman.

**The header**
<img width="969" alt="header" src="https://user-images.githubusercontent.com/39203530/74672991-5f9ada80-517c-11ea-9b75-7ca81d2870e0.png">

**The body**
<img width="967" alt="rawdata" src="https://user-images.githubusercontent.com/39203530/74673085-8ce78880-517c-11ea-95a2-2462a4d5eb57.png">

**Response**
<img width="970" alt="reponse" src="https://user-images.githubusercontent.com/39203530/74673106-97a21d80-517c-11ea-8ebe-902e291d6c89.png">

Can you tell me if it's an error on the interop or request side?

**Comment by pmtischler** [comment]
Very likely this is an issue with the request you are generating. HTTP 400 is a `Bad Request` error code. We have continuous integration testing to verify the server accepts valid images.

I'm not sure what you mean by base64. I haven't used postman, so I'm not sure what I'm looking at. Based on the fact I see "raw" rather than "binary", I suspect you're saying that you've taken the data and encoded it as ASCII 1s and 0s representing binary. That's not the same thing as a JPEG or PNG. If you took the content of the HTTP body and put it in a file name `myfile.jpg` or `myfile.png`, it should be able to open in an image viewer/editor.
