### ISSUE TITLE
Running Client Docker on Raspbperry Pi (ARM)

### ISSUE THREAD

**Issue by manavgandhi17** [auvsi-suas/interop#512]
Hey,

I am trying to run the Docker (client) on a RasbPi 4 w/ 8Gb of ram but am having an issue running the container.

It says that I cannot run the container since it was build on an AMD64 host and is not compatible with ARM-based chips. I tried re-building the container for ARM through some resources I found - but none of them were able to successfully build on ARM.

Is this a known incompatibly?

**Comment by pmtischler** [comment]
Yes this is a known incompatibility- the docker images are built for amd64 by default. I've looked into cross-compilation to arm64 in the past to run the prober portion of the client image on Raspberry Pi at competition, but it was complex enough that it wasn't worth it and we just purchased an amd64 machine instead. I think since that attempt there has been increased support for `buildx` and with build stages it may be easier now. That being said, there hasn't been a strong motivation to support it.

Why do you want to use Raspberry Pi? How hard is it to use amd64 instead?

**Comment by manavgandhi17** [comment]
Hey!

That is what I figured. I tried building the git with `buildx` for ARM but ended up running into some errors that were past my base level knowledge of compiling images for Docker.

Our team was mainly looking to use the Raspberry Pi as a compact computer running Ubuntu that serves as our main computer conversing with the Interop server. It would just be running the client side docker and a lightweight GUI that would allow for us to easily interact with the interop server (without needing a whole lot of setup). It is mainly a convenience factor as we would like to build it up into a GCS (similar to those that are sold for UAVs) - thus requiring a compact computer.

We are currently looking into alternatives - but they seem to be much more costly than the Rasbperry Pi.

For now - we are just in the beginning stages, so switching over to an amd-based computer would not be too big of a hassle. Just a bit more costly and we would end up going with a slightly overkill machine like the one [here](https://www.amazon.com/dp/B08QZC6H8Q/).

**Comment by pmtischler** [comment]
The competition uses Intel NUC devices as compact embeddable computers for the same reason. We use [this](https://www.amazon.com/gp/product/B01DJ9XS52) and [this](https://www.amazon.com/gp/product/B00XPVRR5M) model currently, though those are probably outdated at this point.

If you consider the cost of your time and the cost of potential problems, those overkill machines will actually be cheaper.

One thing you should also consider with Raspberry Pi is SD card corruption. The competition used Raspberry Pis for a few things but eliminated them because the SD cards would get corrupted with only a few continuous days of use at the flight line. Limited research made it seem that it was related to OS logs and that mounting them in tmpfs (RAM) would eliminate the issue, but it wasn't worth the hassle. By contrast, the Intel NUC devices use much better storage which is very unlikely to suffer the same type of problems.

As we're unlikely to invest in ARM at this time, I'm going to close this issue. Best of luck!
