### ISSUE TITLE
WGS 84 to Mercator Projection for Mapping

### ISSUE THREAD

**Issue by kushnayak** [auvsi-suas/interop#514]
https://github.com/auvsi-suas/interop/blob/9a9202fe4185ecd85c1175fd83d4946c675dcb19/server/auvsi_suas/views/missions.py#L258-L273
For the mapping task, missions.py seems to be transforming the WGS 84 map center position to the mercator projection, adding the height/width meters to the mercator-projected point to find the map vertices, and then converting these points back to WGS 84. However, the mercator projection distorts distances, so the map height/width ultimately decreases by performing this transformation.

Is this intended for the mapping task, where the map height does not represent the true height, but rather the height after being transformed by the mercator projection? If not, then I suggest `wgs_to_web_mercator.transform()` be changed to `wgs_to_utm.transform()` to reflect the true distances for mapping.

**Comment by pmtischler** [comment]
From the competition rules:

> WGS 84 Web Mercator Projection. Teams must generate a map conforming to the Web
Mercator projection, the standard format for web mapping and historically used by services like
Google Maps. Teams will be given a GPS position, which must be the center of the generated
map, and a height in feet, which must be the distance covered by the height of the map.

Are you saying that the calculation done in `missions.py` does not reflect the rules, is doing the web mercator calculation incorrectly, or that the rules should be changed to use a UTM projection?

With the caveat I'm not an expert on these projections- my understanding is that what you say regarding changing distances under the web mercator projection is accurate, and I also believe it's supposed to be imperceivable at the scale of the map. The benefit of web mercator is improved angles and a more natural look, which is why systems like Google Maps use this projection.

**Comment by kushnayak** [comment]
I apologize, I must have overlooked the rules which stated that the map conforms to the Web
Mercator projection, making the transformation in `missions.py` correct. Some of the confusion also stemmed from the fact that even at the scale of the map, the Web Mercator projection distorted distances. For example on the sample mission, the .kml file generated showed the map having a height of around 930 ft, while the actual map height was supposed to be 1200 ft.
