### ISSUE TITLE
Map Display not Working

### ISSUE THREAD

**Issue by KrishnanS2006** [auvsi-suas/interop#519]
Hello,

Following up on #518, I have successfully submitted the Map to the Interop server (it is shown in the Admin Dashboard). However, navigating to the `/api/maps/1/testuser` URL displays a "Map not found." page. I also cannot click on the image link (`/media/maps/1-2_G9OdI3u.JPEG`), as it shows a URL Not Found error, even for just the base route (`/media`). Am I doing something wrong? Thanks for the help!

![image](https://user-images.githubusercontent.com/62958782/140625157-fdbbf727-5bc5-4230-9963-9a3c09826ac4.png)
![image](https://user-images.githubusercontent.com/62958782/140625143-0bc6cb9c-9155-40bc-99f7-3f5a259a5e8b.png)
![image](https://user-images.githubusercontent.com/62958782/140625149-9df73d77-a80e-489b-baf2-934cb079d731.png)

**Comment by pmtischler** [comment]
Thank you for catching a bug! There was an issue where the map view code was using the request's user rather than the URL's user, so a superuser wouldn't actually be able to review the maps. I've added a test case for this and pushed the fix.

I've also added a readonly field to the model so that the URL link is directly viewable, rather than having to craft it yourself. This should also help people avoid the `/media` URL.

The `/media` URLs are not expected to work because they are intentionally disabled. The path listed is the path on disk at the server, which you could use to read as a superuser. The web-serving functionality is disabled because it doesn't support permissions/ACLs, so if we allowed it then users could reach each other's maps.
