### ISSUE TITLE
failing running Dockerfile in client directory

### ISSUE THREAD

**Issue by coolpig123** [auvsi-suas/interop#534]
when building the docker directory to get the client library, it throws me the next issue : 
"Step 5/10 : COPY client/requirements.txt .
COPY failed: file not found in build context or excluded by .dockerignore: stat client/requirements.txt: file does not exist"
is there maybe an older version of docker to get the library, of am i installing the library wrong?

**Comment by pmtischler** [comment]
To use the client image you do not need to build it- the commands to run it will pull the prebuilt image down from docker hub. Please follow the README's Getting Started.

The error is most likely because you are not executing the build command correctly, so the working directory you are executing docker from is incorrect so it can't find the file at the right relative path. If you are trying to build it due to customizations, you should use [interop-client.sh](https://github.com/auvsi-suas/interop/blob/master/client/interop-client.sh) which executes the command correctly.

Beyond this, I suggest you learn Docker so you know how to troubleshoot it yourself.
